
#db.oracle.aami.username = aami
#db.oracle.aami.password = jBAkNzyitcDRTFwG4amUmrwYkIpyGswj
#db.oracle.aami.url = jdbc:oracle:thin:@172.26.56.110:1521:aami

#db.oracle.amis.username = fly
#db.oracle.amis.password = 2CqMBEKV6hNypkYo3UgaIaWn2O3sh1eN
#db.oracle.amis.url = jdbc:oracle:thin:@190.1.61.15:1523/sidamis

db.oracle.aami.username = aami
db.oracle.aami.password = e7Jo9+7KjvsuU8MQs3kDqgzAF7LgS8LF
db.oracle.aami.url = jdbc:oracle:thin:@10.2.10.8:1521:aami

db.oracle.amis.username = amis
db.oracle.amis.password = KSb+cQyGGMHT8fU8HUcUtuCQrDd0oYIn
db.oracle.amis.url = jdbc:oracle:thin:@10.2.10.8:1521:aami